### ISSUE TITLE
Prompt outputs failed validation

### ISSUE THREAD

**Issue by botnang** [chaojie/ComfyUI-I2VGEN-XL#2]
got prompt
ERROR:root:Failed to validate prompt for output 6:
ERROR:root:* VHS_LoadVideoPath 5:
ERROR:root:  - Return type mismatch between linked nodes: video, {} != STRING
ERROR:root:Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

![image](https://github.com/chaojie/ComfyUI-I2VGEN-XL/assets/32015065/7921fbcc-2f51-4229-b46c-3204ce2176f2)

**Comment by botnang** [comment]
![image](https://github.com/chaojie/ComfyUI-I2VGEN-XL/assets/32015065/8f4a76cd-046d-46d4-9cc8-e28df39003af)

**Comment by chaojie** [comment]
@botnang I changed the type to `STRING`, you can git pull & test again
